### ISSUE TITLE
option to not erase flash?

### ISSUE THREAD

**Issue by proddy** [emsesp/EMS-ESP-Flasher#4]
@MichaelDvP is it possible to not erase the flash when uploading a new firmware? As this will remove all the settings.

**Comment by MichaelDvP** [comment]
Sure, we can just remove these lines or set arguments -no_erase somewhere else (need to search).
I'll check and make a PR also with new 16M partitions.
Edit: these lines:
https://github.com/emsesp/EMS-ESP-Flasher/blob/9b7872302ba4d6f06cb798170aad575c8164ff14/esp_flasher/__main__.py#L174-L178

**Comment by proddy** [comment]
Added to 1.0.2. Thanks Michael.

Now we just need to create a release and add the binary assets

**Comment by MichaelDvP** [comment]
Hmm, the new 16M partition scheme will repartion and configs are lost. Maybe leave the old scheme for now and first dicuss if we add a failsafe factory partition additional to ota-1/2 on the 16M.

**Comment by proddy** [comment]
8MB added by Michael

**Comment by bbqkees** [comment]
I only noticed this now but can you make a checkbox or so to make erasing the flash optional?

I often have customers who have messed up their config, bricked their device or have other issues that would need or could use a full flash erase. F.i. they lost their password, have reboot loops, and if they set the wrong board profile the reset button also does not work.
Other use case is when someone wants to sell their Gateway and want to make sure nothing of their old config remains on the device.

There is no other easy way to flash EMS-ESP without this specific flash tool.

**Comment by proddy** [comment]
That could be added. It's some tricky python code.

There's also another option - press and hold the button for 10 seconds

see https://emsesp.github.io/docs/FAQ/#how-to-hardware-reset

**Comment by bbqkees** [comment]
> That could be added. It's some tricky python code.
> 
> There's also another option - press and hold the button for 10 seconds
> 
> see https://emsesp.github.io/docs/FAQ/#how-to-hardware-reset

Yes indeed but that hardware reset is actually an EMS-ESP software function set to a GPIO.
If the board profile is incorrectly set or the whole thing is in a kind of boot loop or something else this won't work.
Also the reset button is on the inside of the Gateway products so you need to unscrew the case.
For the S3 and S32 this is easy but the new E32 V2 is more difficult to unscrew and assemble again.

When someone reports an issue with their product, first thing is the obvious reboot, unplug/plug, web interface reset etc.

The 'full flash erase and flash a stable EMS-ESP bin file' procedure is usually then my second thing to try because that can rule out a lot and I think in about 50% of all cases the issue is solved by doing this.

**Comment by proddy** [comment]
I started making the changes, but haven't finished it yet. So it's broken. I'll find some time this week to fix it

**Comment by proddy** [comment]
okay, should work now. Version 1.0.3

**Comment by proddy** [comment]
i was editing on two different machines (a MacBook and a windows desktop) and forgot to publish the PR. It's merged now

**Comment by proddy** [comment]
I had to revert the changes when upgrading the frontend to Qt, so need to re-implement the erase feature

**Comment by proddy** [comment]
fixed in v1.1.0 - https://github.com/emsesp/EMS-ESP-Flasher/releases/tag/v1.1.0
